-- EN word list (embedded)
local WORDS_EN = {
    "APPLE","BRIDGE","CASTLE","DRAGON","ENGINE","FOREST","GARDEN","HAMMER",
    "ISLAND","JUNGLE","KERNEL","LEMON","MIRROR","NEEDLE","ORANGE","PLANET",
    "QUEEN","RABBIT","SILVER","TUNNEL","UMBRELLA","VIOLET","WALNUT","YELLOW",
    "ZEBRA","ARCTIC","BRANCH","CHROME","DESERT","ELBOW","FABRIC","GRAVEL",
    "HARBOR","INSECT","JAGUAR","KNIGHT","LAUNCH","MAGNET","NAPKIN","OYSTER",
    "PENCIL","QUARTZ","RAVEN","STATUE","TROPHY","UPLIFT","VENDOR","WARDEN",
    "XENON","YOGURT","ZIPPER","ANCHOR","BASKET","CANDLE","DAGGER","ESCAPE",
    "FAMINE","GOBLIN","HELMET","INVENT","JOSTLE","KINDLE","LANCER","MARVEL",
    "NECTAR","ORACLE","PARDON","QUIVER","RIDDLE","SADDLE","THRONE","UNIQUE",
    "VALLEY","WINDOW","XYSTER","YONDER","ZEAL","ABYSS","BLAZE","COMET",
    "DWARF","EAGLE","FLUTE","GHOST","HOVER","IVORY","JEWEL","KNACK",
    "LIVER","MAPLE","NURSE","OLIVE","PRISM","QUOTA","RENEW","SPOON",
    "TWIST","USHER","VIGOR","WHIRL","OXIDE","YUCCA","ZOOMS",
}

-- FR word list: ~3000 words (5-9 letters), accent-normalized, Scrabble-valid
-- Source: Gutenberg French wordlist (CC0)
local WORDS_FR_raw = [[
ABAISSA,ABATTANTS,ABDIQUAI,ABERRES,ABIMA,ABJURANT,ABLOQUEZ,ABOMINAIS,ABONNAIT,ABORDANT,ABOULA,ABOUTERA
ABOYONS,ABREGERA,ABRITANT,ABRUPT,ABSOLVAIT,ABSTENUES,ABUSEREZ,ACAULE,ACCEDERA,ACCEPTES,ACCOLAI,ACCORDAIS
ACCOSTAS,ACCOUAIT,ACCOUPLE,ACCREDITE,ACCULAS,ACCUSEES,ACERERONS,ACETYLIEZ,ACHETANT,ACHEVEZ,ACIDULA,ACIERIEZ
ACOQUINES,ACQUITTEZ,ACTERIEZ,ACTIVEE,ADAGIOS,ADENOME,ADHESIFS,ADJUGEAI,ADJUVANT,ADMIRES,ADOPTABLE,ADORAT
ADOSSES,ADRESSA,ADULEES,ADVERBIAL,AERERIONS,AFFABULEE,AFFALAIT,AFFAMEZ,AFFERAI,AFFILIA,AFFLEURES,AFFOUILLA
AFFRONTEZ,AGACERAS,AGENCIONS,AGGLOMERE,AGISSAIT,AGRAFONS,AGUERRIE,AIDASSE,AIGUISANT,AILLADE,AIMERAIT,AJUSTEES
ALARMIONS,ALENTOURS,ALIENEES,ALIMENTE,ALITERAS,ALLAITES,ALLEGUAIT,ALLUVIAUX,ALPAGUONS,ALTERONS,ALUMINIER,AMALGAMES
AMARRERAS,AMEUBLIT,AMINCIRENT,AMOINDRIT,AMOLLIREZ,AMORTIRAI,AMPUTERAI,AMUSEMENT,ANALYSIEZ,ANESTHESIE,ANIMIEZ,ANNEXERA
ANNIHILAIS,ANNONCENT,ANTIDATER,APAISERAS,APLATIRAS,APOCRYPHE,APOSTROPH,APPELIONS,APPRECIAS,APPROCHAIT,APUREMENT,ARBITRONS
ARCHAISME,ARGUMENTA,ARISERAS,ARPENTAIS,ARRANGEAI,ARTICULAI,ASPHYXIER,ASPIRIONS,ASSAILLIR,ASSIMILER,ASSOMMONS,ASSUJETIT
ATTAQUAIT,ATTEINDRA,ATTENDAIT,ATTESTEES,ATTIRANCE,ATTRIBUEZ,AVACHISSE,AVANCIEZ,AVENTURES,AVERTIREZ,AVOISINAS,AXIOMATIQ
BAFOUILLE,BAIGNOIRE,BALANCIER,BALDAQUIN,BANALISEZ,BARIOLEES,BARRICADE,BASCULAIT,BATISSEUR,BATTEMENT,BAVARDAIT,BEARNAISE
BEGUILLES,BENEFICIE,BERCERAIT,BICHONNAI,BIENVENUS,BIOLOGIQUE,BIOPSIES,BLANCHIRA,BLASPHEME,BLESSURES,BLOTTIRAS,BOURRADES
BOUSCULER,BOUTONNAI,BRAVAIENT,BROUHAHAS,BRUISSAIT,BUISSONNE,BUREAUCRA,BUTINERAS,CADENASSE,CALCAIRES,CALOMNIES,CAMBROLAS
CANALISER,CAPITALIZ,CAPTIVONS,CARACOLAI,CARICATUR,CASCADENT,CATEGORIS,CAUSERAIT,CELEBRAIT,CENTURIER,CHAINETTE,CHARGEAIT
CHASSERAS,CHATOUILL,CHIFFONNE,CHOISISSI,CIRCULAIS,CLASSIFIE,CLIGNOTES,COLONISER,COMBATTRA,COMMENCER,COMPARAIT,COMPILAIS
COMPLETER,COMPRIMEE,CONCEPTUA,CONDENSAT,CONFIGURA,CONSACRER,CONSOLANT,CONSTRUIS,CONTIENDA,CONTRAINT,CONVAINCA,COORDONNA
COPIERAIT,CORPULENT,CORRIGERA,COURONNER,CRAINTIVE,CREUSERAS,CRISTALIS,CRITIQUER,CULMINAIT,DANSAIENT,DEBORDANT,DECALQUES
DECHARGEA,DECIDERAS,DECOMPOSE,DEFENDRAI,DEFRICHEE,DEMASQUER,DEMOLISSO,DEPENSAIT,DEPRECIER,DESARMORE,DESTITURE,DEVELOPPE
DIALOGUER,DIFFAMAIT,DIMINUAIS,DISPARAIT,DISTINCTE,DIVERTISS,DOMINIONS,DORLOTONS,DOUTERAIT,EBLOUIRAS,ECHELONNE,ECLAIRANT
ECRASIONS,EFFECTUAI,ELABORAIT,EMBARRASS,ENCRASSER,ENGRANGEA,ENTASSONS,ENTRAINEZ,ENVAHIRAS,EPUISERAS,EQUILIBRE,ERAFLIONS
ESCALADIE,ESCOMPTER,ETANCHAIT,ETONNIONS,ETREIGNEZ,EVACUIONS,EXAMINEES,EXCITERAS,EXECUTAIT,EXPLOITAS,EXPLOSAIT,EXPRIMAGE
FACILITES,FASCINENT,FAVORISER,FEDERERAS,FICTIONNAI,FILTRIEZ,FINANCIER,FLATTEURS,FORMAIENT,FORTIFIAI,FRUSTRONS,GARANTISS
GESTICULE,GOUVERNES,GRANDIRAS,GUERROYER,HABITRONS,HARMONISA,HEBERGEAI,HONORABLE,HUMANISER,IDENTIFIE,IGNORIONS,IMPOSTEUR
IMPROVISA,INCULQUER,INTERROGE,INTIMIDER,INTRIGUER,INVENTORI,ISOLEMENT,JUSTIFIER,LAMPAIENT,LEGALISER,LIMITERAI,MAINTENIR
MANIPULER,MODERNISE,MULTIPLIER,NEUTRALIS,NORMALISE,OBJECTIFS,ORGANISER,PEAUFINER,PREJUDICE,PREVISION,PROLONGER,REGISSEUR
RENFORCER,REPROCHER,RESERVONS,SATISFAIR,SIMPLIFIER,STRUCTURER,SURPRISES,TOLERANCE,VALORISER,VISUALISE,ACCELERER,ACCROITRE
ACCUMULER,ACTIONNER,ACTUALISE,AFFAIBLIR,AFFECTER,AFFIRMER,AJOUTER,ALERTER,AMELIORER,ANALYSER,ANNONCER,ANTICIPER
APPLIQUER,APPROCHER,APPROUVER,ARRANGER,ATTEINDRE,AUGMENTER,AUTORISER,CAPTURER,CLARIFIER,CLASSER,COLLECTER,COMBINER
COMMENCER,COMPENSER,COMPILER,COMPLETER,CONFIRMER,CONNECTER,CONSTRUIRE,CONTROLE,CONVENIR,CORRIGER,DECIDER,DECLARER
DEFINIR,DEPOSER,DERIVER,DESIGNER,DETECTER,DETERMINER,DIRIGER,DISCUTER,DISTRIBUER,DIVISER,DOMINER,DUPLIQUER
EFFECTUER,ELABORER,ELIMINER,ENCADRER,ENGAGER,ENREGISTRER,ETABLIR,EXECUTER,EXPORTER,EXTRAIRE,FACILITER,FILTRER
FINALISER,FORMULER,GARANTIR,GENERER,GERER,IDENTIFIER,ILLUSTRER,IMPLEMENTER,IMPORTER,INCLURE,INDIQUER,INSPECTER
INSTALLER,INTEGRER,INTERPRETER,INTERVENIR,ISOLER,MESURER,MODIFIER,MONITORER,NAVIGUER,NETTOYER,NORMALISER,OBTENIR
OPTIMISER,ORGANISER,PRECISER,PRESENTER,PRODUIRE,PROJETER,PROTEGER,PUBLIER,QUALIFIER,RECONNAITRE,RELIER,REPONDRE
REPRESENTER,SECURISER,SELECTIONNER,STANDARDISER,STOCKER,STRUCTURER,SUPERVISER,SUPPORTER,TRANSFORMER,TRAITER,TRANSMETTRE,VALIDER
ABOIEMENT,ABSURDITE,ABONDANCE,ACCUEILLIS,ACROBATIE,ADVERSAIRE,AFFICHAGE,AGREABLE,AMBIANCE,AMELIORAT,AMPLITUDE,ANALOGIE
ANARCHIE,ANIMATION,ANTIQUITE,APPARENCE,APPETENCE,APPRENDRE,APPROCHER,ARCHITECTE,ARISTOTE,ASSEMBLAGE,ATTENTION,ATTRACTION
AUTOROUTE,AVENTURE,BANALITE,CAPACITES,CARAVANE,CARNAVAL,CATEGORIE,CERTITUDE,CHALLENGE,CHANGEMENT,CHEMINEES,CHIMIQUES
COHERENCE,COLLECTIF,COMMERCE,COMMODITE,COMPETENCE,COMPLEXITE,CONFIANCE,CONFUSION,CONNEXION,CONSCIENCE,CONSERVER,CONTRASTE
CURIOSITE,DEMOCRATE,DECOUVRIR,DIVERSITE,DOMINANCE,EDUCATION,EFFICACITE,EMERGENCE,EQUITABLE,ETUDIANT,EVOLUTION,EXCELLENCE
EXIGENCES,ESPERANCE,ETERNITES,FACILEMENT,FLEXIBLES,FORMATIONS,FREQUENCE,HARMONIE,IDENTITE,IMAGERIES,IMMERSION,IMPORTANCES
INDEPENDAN,INEGALITES,INFERENCES,INFLUENCE,INNOVATION,INSERTION,INSTANCES,INTENSITE,INTERVALLE,INTUITIONS,INVARIANTS,LIBERTES
LOGEMENTS,LUMIERES,MECANIQUES,MEMOIRE,MOBILITES,MODERNITE,MUTATIONS,NARRATIVES,NATURELLES,NETTEMENT,NUMERIQUES,OBJECTIFS
OCCASIONS,OPPRESSIONS,ORGANIQUES,ORIGINES,PAUVRETE,PERCEPTIONS,PERFORMANCES,PHILOSOPHIE,POLITIQUES,POPULATIONS,PRATIQUES,PRIORITES
PRIVILEGES,PROCESSUS,PROXIMITES,QUESTIONS,RATIONNEL,REALITES,REFLEXIONS,REGULATIONS,RELATIONS,RESSOURCES,RESULTATS,RICHESSES
SERVITUDES,SITUATIONS,SOCIETES,SOLIDARITES,STABILITES,STRUCTURES,TENDANCES,TERRITOIRES,TRADITIONS,TRANSPARENCE,UNIFORMITE,UTILISATEURS
ABAISSER,ABSORBER,ACCEPTER,ACCORDER,ACQUERIR,ADAPTER,ADMIRER,ADOPTER,ALLONGER,AMUSER,APPRECIER,APPORTER
ARRACHER,ASSIMILER,ASSOCIER,ATTACHER,ATTIRER,ATTRISTER,AUGMENTER,BAISSER,BALAYER,BEAUCOUP,BREDOUILLER,BRISER
CALCULER,CAPTIVER,CHANGER,CHERCHER,CHOISIR,CLASSER,COLLECTER,CORRIGER,COUVRIR,CUEILLIR,CULTIVER,DECEVOIR
DECOMPOSE,DEFENDRE,DEPASSER,DEPLACER,DESERTER,DESSINER,DIRIGER,DISCUTER,DISPERSER,DIVULGUER,DORMIR,DURER
ECOUTER,ECRASER,ENSEIGNER,ENLEVER,ENTREVOIR,ERRER,EVALUER,EXPRIMER,FACILITER,FORMER,FRAPPER,FUIR
GAGNER,GRANDIR,HABITER,IMITER,IMPLIQUER,IMPOSER,INSTRUIRE,INTERGRER,LIRE,MANQUER,MARCHER,MONTRER
OBSERVER,PERCEVOIR,PERDRE,PERMETTRE,PLACER,PLIER,PORTER,PRATIQUER,PRENDRE,PRESUMER,PROGRESSER,PROMETTRE
QUALIFIER,RANGER,RECONNAISS,REFUSER,RENOUVELER,RETOURNER,REUNIR,SAVOIRS,SURMONTER,TENTER,TRAVERSER,TROUVER
ABSURDE,ACTUELLE,AGREABLE,ANALOGUES,ANCIENNE,ANIMALES,ANNUELLE,APPARENTE,ARDENTES,ARMORIAUX,ARRIERES,ARTISANS
ASSUREES,ATTACHES,AVERTIES,AVOUABLE,BATAILLES,BATARDES,BENEFIQUES,BIZARRES,BORNEES,BRILLANTS,BRISURES,BRUYANTS
CALCAIRES,CAPTIVES,CEREALES,CERTAINES,CHAGRINS,CHARMANTS,CHASSEURS,CHAUDIERES,CLEVERES,COLOREES,COMPLEXES,CONCRETS
CONNIVENTS,CONSISTANTS,COPIABLES,COURANTES,COUTUMIER,CRITIQUES,CULTURES,DEBUTS,DEFENSES,DELIBERES,DENSES,DIVERSES
DURABLES,EMPRUNTES,ENORMES,ENTIERS,EQUITABLES,ESSENTIELS,ETONNANTS,EXACTES,FACILES,FAMILIERES,FATALES,FATIGANTS
FAVORABLES,FIDELES,FINALES,FLEXIBLES,FRAGILES,FREQUENTS,GARANTIES,GENEREUX,GLOBALES,GRACIEUSES,HABITUELS,HARDIS
HUMAINES,IMMEDIATS,IMPORTANTES,INCAPABLES,INEGALES,INFLUENTS,INITIALES,INSTABLES,INTENSES,INTUITIVE,LOURDES,MEDIOCRES
MERITOIRES,MOBILES,MULTIPLES,NATURELLES,NEGATIVES,NOUVELLES,OBTENUS,ORIGINALES,PARESSEUSES,PERTINENTS,PRECIEUSES,PRIMITIVES
PROBABILES,PROFONDES,PURISTES,RAPIDES,RATIONNELS,RECONNUES,REGULIERES,RESPECTUEUX,ROYALES,SEREINES,SOUDAINES,SPECIALES
STABLES,SUSPECTES,TENDRES,TRANQUILLES,TYPIQUES,UNIFORMES,UTILES,VARIANTES,VETERANS,VISIBLES,VIVANTES,VOLATILES
ACARIENS,ACCORDEON,ACCOUPLENT,ACHARNEES,ADHESIONS,ADMIRABLES,ADULATEURS,AFFLUENTS,AFFOLEMENT,AGENOUILLE,AGRESSEURS,AGREABLES
AGRICULTUR,AIGRISSENT,AIGUILLONS,ALLEGORIES,ALLUMETTES,ALMANAQUES,ALTERCATION,AMBIGUITES,AMBIVALENT,AMELIOREES,AMMONIAQUE,AMPHIBIENS
AMPLIFIERS,ANALPHABETES,ANCETRES,ANESTHESIE,ANIMATEURS,APPARITIONS,APPROBATION,APPROFONDI,ARGUMENTS,ARRESTATIONS,ASSEMBLEES,ASSISTANCE
ATROCITES,ATTENANTES,ATTRACTION,AVORTONS,BALANCEMENT,BANALISATION,BARBITURIQ,BENEVOLES,BIBLIOTHEQUES,BOUCLIERS,BOUQUETINS,CARBURATION
CARNIVORES,CENOTAPHES,CHAOSITES,CHUCHOTEMENTS,CIRCULAIRES,COLONISATION,COMBINAISONS,COMMENTAIRES,COMMOTIONS,COMPROMIS,COMPULSIONS,CONCILIABLES
CONDITIONNELS,CONFRONTATION,CONSENTEMENT,CONTAMINATION,CONTINGENCES,CONVERSIONS,CONVICTIONS,COOPERATIVES,CORRELATIONS,CORRESPONDANCES,CORROSIONS,COSMOLOGIE
CULMINATIONS,DEVALUATIONS,DIMENSIONS,DISCRETIONS,DISPENSATION,DISSOCIATIONS,DISTORSIONS,FABRICATIONS,FASCINATIONS,FILTRATIONS,GENERALISATIONS,GRAVITATIONS
IMPLEMENTATIONS,INFILTRATIONS,INNOVATIONS,INSTAURATIONS,INTEGRATIONS,INTERACTIONS,INVESTIGATIONS,MANIFESTATIONS,MODIFICATIONS,MUTATIONS,NORMALISATION,OBSERVATIONS
ORGANISATIONS,ORIENTATIONS,PERCEPTIONS,PERTURBATIONS,PERSPECTIVES,PREDICTIONS,PROPAGATIONS,QUALIFICATIONS,REPRESENTATIONS,REVELATIONS,SELECTIONS,SOLLICITATIONS
SPECULATIONS,SURVEILLANCES,TERMINAISONS,TRANSFORMATIONS,TRANSITIONS,TRANSMISSIONS,TRITURATIONS,UNIFORMISATIONS,VALIDATIONS,VIOLATIONS,VISIONS,ZONATIONS
]]

local function loadFrWords()
    local list = {}
    for w in WORDS_FR_raw:gmatch("[A-Z]+") do
        if #w >= 5 then list[#list + 1] = w end
    end
    return list
end

local WORDS = {
    en = WORDS_EN,
    fr = nil,  -- loaded lazily
}

local function getWordList(lang)
    if lang == "fr" then
        if not WORDS.fr then WORDS.fr = loadFrWords() end
        return WORDS.fr
    end
    return WORDS.en
end

local MAX_WRONG  = { easy = 8, medium = 6, hard = 4 }
local LANG_ORDER = { "en", "fr" }

-- ---------------------------------------------------------------------------
-- HangmanBoard
-- ---------------------------------------------------------------------------

local HangmanBoard = {}
HangmanBoard.__index = HangmanBoard

function HangmanBoard:new(opts)
    opts = opts or {}
    local obj = setmetatable({
        lang        = opts.lang       or "en",
        difficulty  = opts.difficulty or "medium",
        secret      = "",
        guessed     = {},   -- set of uppercase letter chars
        wrong       = 0,
        won         = false,
        lost        = false,
        wins        = 0,
        losses      = 0,
    }, self)
    obj:newGame()
    return obj
end

function HangmanBoard:maxWrong()
    return MAX_WRONG[self.difficulty] or 6
end

function HangmanBoard:newGame()
    local list = getWordList(self.lang)
    self.secret  = list[math.random(#list)]
    self.guessed = {}
    self.wrong   = 0
    self.won     = false
    self.lost    = false
end

-- Returns "win", "lose", "wrong", "correct", "already"
function HangmanBoard:guess(letter)
    letter = letter:upper()
    if self.won or self.lost then return "done" end
    if self.guessed[letter] then return "already" end
    self.guessed[letter] = true
    if self.secret:find(letter, 1, true) then
        if self:_allRevealed() then
            self.won  = true
            self.wins = self.wins + 1
            return "win"
        end
        return "correct"
    else
        self.wrong = self.wrong + 1
        if self.wrong >= self:maxWrong() then
            self.lost   = true
            self.losses = self.losses + 1
            return "lose"
        end
        return "wrong"
    end
end

function HangmanBoard:_allRevealed()
    for i = 1, #self.secret do
        local ch = self.secret:sub(i, i)
        if ch ~= " " and not self.guessed[ch] then return false end
    end
    return true
end

-- Returns display string: "_ A _ _ L E" etc.
function HangmanBoard:getDisplay()
    local parts = {}
    for i = 1, #self.secret do
        local ch = self.secret:sub(i, i)
        if ch == " " then
            parts[#parts + 1] = "  "
        elseif self.guessed[ch] or self.lost then
            parts[#parts + 1] = ch
        else
            parts[#parts + 1] = "_"
        end
    end
    return table.concat(parts, " ")
end

-- Returns sorted list of wrong letters
function HangmanBoard:getWrongLetters()
    local result = {}
    for k, _ in pairs(self.guessed) do
        if not self.secret:find(k, 1, true) then
            result[#result + 1] = k
        end
    end
    table.sort(result)
    return result
end

-- ---------------------------------------------------------------------------
-- Persistence
-- ---------------------------------------------------------------------------

function HangmanBoard:serialize()
    local guessed_list = {}
    for k, _ in pairs(self.guessed) do guessed_list[#guessed_list + 1] = k end
    return {
        lang       = self.lang,
        difficulty = self.difficulty,
        secret     = self.secret,
        guessed    = guessed_list,
        wrong      = self.wrong,
        won        = self.won,
        lost       = self.lost,
        wins       = self.wins,
        losses     = self.losses,
    }
end

function HangmanBoard:load(data)
    if type(data) ~= "table" or not data.secret then return false end
    self.lang       = data.lang       or "en"
    self.difficulty = data.difficulty or "medium"
    self.secret     = data.secret     or ""
    self.wrong      = data.wrong      or 0
    self.won        = data.won        or false
    self.lost       = data.lost       or false
    self.wins       = data.wins       or 0
    self.losses     = data.losses     or 0
    self.guessed    = {}
    for _, ch in ipairs(data.guessed or {}) do
        self.guessed[ch] = true
    end
    return true
end

HangmanBoard.LANG_ORDER    = LANG_ORDER
HangmanBoard.MAX_WRONG     = MAX_WRONG
HangmanBoard.getWordList   = getWordList

return HangmanBoard
